package org.development.exam_online.service;

import org.development.exam_online.common.PageResult;
import org.development.exam_online.dao.dto.AutoGeneratePaperRule;
import org.development.exam_online.dao.entity.ExamPaper;

import java.util.List;
import java.util.Map;

/**
 * 试卷服务接口
 */
public interface ExamPaperService {

    ExamPaper createPaper(ExamPaper examPaper);

    String addQuestionsToPaper(Long paperId, List<Long> questionIds, List<Double> scores);

    String removeQuestionsFromPaper(Long paperId, List<Long> questionIds);

//    Map<String, Object> generatePaperByTemplate(org.development.exam_online.dao.dto.TemplateGenerateRequest request);

    Map<String, Object> previewTemplateGeneration(org.development.exam_online.dao.dto.TemplateGenerateRequest request);

    String saveAutoGeneratedPapers(Long paperId, List<Long> questionIds, List<Double> scores);

    Map<String, Object> getPaperById(Long paperId);

    Map<String, Object> previewPaper(Long paperId);

    String updatePaper(Long paperId, ExamPaper examPaper);

    String deletePaper(Long paperId);

    PageResult<ExamPaper> getPaperList(Integer pageNum, Integer pageSize, String keyword, String type, Long createdBy);

    List<Map<String, Object>> getPaperQuestions(Long paperId);

    Double calculateTotalScore(Long paperId);

    String clearAllQuestions(Long paperId);
}
