package org.development.exam_online.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.development.exam_online.common.PageResult;
import org.development.exam_online.common.Result;
import org.development.exam_online.common.enums.PaperTemplate;
import org.development.exam_online.dao.dto.AutoGeneratePaperRule;
import org.development.exam_online.dao.dto.TemplateGenerateRequest;
import org.development.exam_online.dao.entity.ExamPaper;
import org.development.exam_online.security.RequirePermission;
import org.development.exam_online.service.ExamPaperService;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Tag(name = "试卷管理", description = "试卷管理接口（手动组卷、自动组卷、试卷预览、发布等）")
@RestController
@RequestMapping("/api/exam-papers")
@RequiredArgsConstructor
@RequirePermission({"paper:manage"})
public class ExamPaperController {

    private final ExamPaperService examPaperService;

    @Operation(summary = "创建试卷")
    @PostMapping
    public Result<ExamPaper> createPaper(@Valid @RequestBody ExamPaper examPaper) {
        ExamPaper createdPaper = examPaperService.createPaper(examPaper);
        return Result.success(createdPaper);
    }

    @Operation(summary = "手动组卷-添加题目")
    @PostMapping("/{paperId}/questions")
    public Result<String> addQuestionsToPaper(
            @PathVariable Long paperId,
            @RequestBody List<Long> questionIds,
            @RequestParam(required = false) List<Double> scores) {
        String message = examPaperService.addQuestionsToPaper(paperId, questionIds, scores);
        return Result.success(message);
    }

    @Operation(summary = "手动组卷-移除题目")
    @DeleteMapping("/{paperId}/questions")
    public Result<String> removeQuestionsFromPaper(
            @PathVariable Long paperId,
            @RequestBody List<Long> questionIds) {
        String message = examPaperService.removeQuestionsFromPaper(paperId, questionIds);
        return Result.success(message);
    }

//    @Operation(summary = "模板组卷")
//    @PostMapping("/template-generate")
//    public Result<Map<String, Object>> generatePaperByTemplate(
//            @Valid @RequestBody org.development.exam_online.dao.dto.TemplateGenerateRequest request) {
//        Map<String, Object> result = examPaperService.generatePaperByTemplate(request);
//        return Result.success(result);
//    }

    @Operation(summary = "预览模板组卷结果")
    @PostMapping("/template-generate/preview")
    public Result<Map<String, Object>> previewTemplateGeneration(
            @Valid @RequestBody TemplateGenerateRequest request) {
        Map<String, Object> result = examPaperService.previewTemplateGeneration(request);
        return Result.success(result);
    }

    @Operation(summary = "获取试卷模板列表")
    @GetMapping("/templates")
    public Result<List<Map<String, Object>>> getTemplates() {
        List<Map<String, Object>> templates = new ArrayList<>();
        for (PaperTemplate template : PaperTemplate.values()) {
            Map<String, Object> info = new HashMap<>();
            info.put("code", template.getCode());
            info.put("name", template.getName());
            info.put("description", template.getDescription());
            info.put("defaultTotalQuestions", template.getDefaultTotalQuestions());
            info.put("defaultTotalScore", template.getDefaultTotalScore());
            info.put("typeRules", template.getTypeRules());
            info.put("defaultDifficultyRatio", template.getDefaultDifficultyRatio());
            templates.add(info);
        }
        return Result.success(templates);
    }

    @Operation(summary = "保存自动组卷结果")
    @PostMapping("/{paperId}/save-auto-generated")
    public Result<String> saveAutoGeneratedPapers(
            @PathVariable Long paperId,
            @RequestBody List<Long> questionIds,
            @RequestParam(required = false) List<Double> scores) {
        String message = examPaperService.saveAutoGeneratedPapers(paperId, questionIds, scores);
        return Result.success(message);
    }

    @Operation(summary = "获取试卷详情")
    @GetMapping("/{paperId}")
    public Result<Map<String, Object>> getPaperById(@PathVariable Long paperId) {
        Map<String, Object> result = examPaperService.getPaperById(paperId);
        return Result.success(result);
    }

    @Operation(summary = "预览试卷")
    @GetMapping("/{paperId}/preview")
    public Result<Map<String, Object>> previewPaper(@PathVariable Long paperId) {
        Map<String, Object> result = examPaperService.previewPaper(paperId);
        return Result.success(result);
    }

    @Operation(summary = "更新试卷信息")
    @PutMapping("/{paperId}")
    public Result<String> updatePaper(
            @PathVariable Long paperId,
            @Valid @RequestBody ExamPaper examPaper) {
        String message = examPaperService.updatePaper(paperId, examPaper);
        return Result.success(message);
    }

    @Operation(summary = "删除试卷")
    @DeleteMapping("/{paperId}")
    public Result<String> deletePaper(@PathVariable Long paperId) {
        String message = examPaperService.deletePaper(paperId);
        return Result.success(message);
    }


    @Operation(summary = "获取试卷列表")
    @GetMapping
    public Result<PageResult<ExamPaper>> getPaperList(
            @RequestParam(defaultValue = "1") Integer pageNum,
            @RequestParam(defaultValue = "10") Integer pageSize,
            @RequestParam(required = false) String keyword,
            @RequestParam(required = false) String type,
            @RequestParam(required = false) Long createdBy) {
        PageResult<ExamPaper> result = examPaperService.getPaperList(pageNum, pageSize, keyword, type, createdBy);
        return Result.success(result);
    }

    @Operation(summary = "获取试卷题目列表")
    @GetMapping("/{paperId}/questions")
    public Result<List<Map<String, Object>>> getPaperQuestions(@PathVariable Long paperId) {
        List<Map<String, Object>> questions = examPaperService.getPaperQuestions(paperId);
        return Result.success(questions);
    }

    @Operation(summary = "计算试卷总分")
    @GetMapping("/{paperId}/total-score")
    public Result<Double> calculateTotalScore(@PathVariable Long paperId) {
        Double totalScore = examPaperService.calculateTotalScore(paperId);
        return Result.success(totalScore);
    }

    @Operation(summary = "清空试卷题目")
    @DeleteMapping("/{paperId}/questions/all")
    public Result<String> clearAllQuestions(@PathVariable Long paperId) {
        String message = examPaperService.clearAllQuestions(paperId);
        return Result.success(message);
    }
}

